### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by updradedsam3000** [RebelKeithy/Metallurgy#3]
the client crashes at mojang (using forge 7.7.0.594 + metalurgy3 alpha)
and gives me this report
- System Details --
  Details:
  Minecraft Version: 1.5
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.7.0_15, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 61083576 bytes (58 MB) / 250347520 bytes (238 MB) up to 954466304 bytes (910 MB)
  JVM Flags: 0 total; 
  AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
  Suspicious classes: FML and Forge are installed
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP v7.42 FML v5.0.31.594 Minecraft Forge 7.7.0.594 8 mods loaded, 8 mods active
  mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
  FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
  Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
  Ideas [Ideas](Metallurgy3.0.0.0.1.jar) Unloaded->Constructed->Pre-initialized
  Metallurgy3Core [Metallurgy 3 Core](Metallurgy3.0.0.0.1.jar) Unloaded->Constructed->Pre-initialized
  Metallurgy3Base [Metallurgy 3 Base](Metallurgy3.0.0.0.1.jar) Unloaded->Constructed->Pre-initialized
  Metallurgy3Machines [Metallurgy 3 Machines](Metallurgy3.0.0.0.1.jar) Unloaded->Constructed->Errored
  Metallurgy3Vanilla [Metallurgy 3 Vanilla](Metallurgy3.0.0.0.1.jar) Unloaded->Constructed->Pre-initialized
  LWJGL: 2.4.2
  OpenGL: GeForce GTX 280/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
  Is Modded: Definitely; Client brand changed to 'forge,fml'
  Type: Client (map_client.txt)
  Texture Pack: Default
  Profiler Position: N/A (disabled)
  Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

java.lang.NullPointerException
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.initMint(MetallurgyMachines.java:188)
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.preInit(MetallurgyMachines.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:515)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:505)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:160)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:406)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:728)
    at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT 173b2c41 ----------

**Comment by Wolverine903** [comment]
I have the same exact crash report

**Comment by ghost** [comment]
I can't run it either, same error.

EDIT: You have to rename the metallurgy jar to "Metallurgy.jar" in order for it to run.

**Comment by updradedsam3000** [comment]
It works, thanks for the info

**Comment by ghost** [comment]
It doesn't work for me. I'm using the latest forge release 7.7.0.595 and minecraft 1.5. Renaming the jarfile didn't seem to have fixed it. I'm going to try forge 7.7.0.594 and I'll tell you later.
EDIT: It keeps crashing. The crash report is the exact same posted above.

**Comment by Wolverine903** [comment]
It should work if you rename it, it fixed the error for me as well.  When you go to mods folder, all you should see is "Metallurgy".

**Comment by ghost** [comment]
That is what I did. I have a jarfile called Metallurgy.jar in my mods folder, and no other mods or coremods. I'm running forge 7.7.0.594 and the latest minecraft stable version, 1.5. Without Metallurgy minecraft runs with no errors. This is what I get, for more detailed information: http://pastebin.com/B2zHcEr2
Thanks for the answers.

**Comment by Wolverine903** [comment]
take the .jar off and have it say just Metallurgy

**Comment by ghost** [comment]
Thanks, I've just tried it. That way minecraft runs, but Metallurgy is not recognised.

EDIT: I think I've found the issue. When minecraft crashes, I can read this error in the console: java.io.FileNotFoundException: ~/.minecraft\mods\Metallurgy.jar (No such file or directory). 
I think my jarfile can't be recognised properly due to the backslashes ( \ ), which are not used in the Linux file system hierarchy, which uses slashes instead ( / ). In Windows I guess it should be running properly, as its file system hierarchy uses backslashes. Should this be reported as a bug?

EDIT (again): I can now confirm the issue, as I've done a little trick. I have renamed my jarfile to Metallurgy.jar and I have also created a file called ".minecraft\mods\Metallurgy.jar" and copied Metallurgy.jar over it, and this way it works, but as you can see this is quite improvised. So the bug would be that Metallurgy doesn't support Linux file system hierarchy, and I presume it doesn't support Mac OS's either, as (I think) it also uses slashes ( / ).

**Comment by SleepingDragon969** [comment]
pjimenez1080 could you please explain further. I am using a MAC and it does nothing but crash. I dont understand how you did what you did to improvise. Or someone please help, I did rename the file to Metallurgy but it did the same thing. Here is the crash report. It appears everything loads but Metallurgy 3 Machines.
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/20/13 2:06 PM
Description: Failed to start game

java.lang.NullPointerException
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.initMint(MetallurgyMachines.java:188)
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.preInit(MetallurgyMachines.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:515)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:505)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:160)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:406)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:728)
    at java.lang.Thread.run(Thread.java:680)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5
    Operating System: Mac OS X (x86_64) version 10.6.8
    Java Version: 1.6.0_43, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 1004096104 bytes (957 MB) / 1071579136 bytes (1021 MB) up to 2675638272 bytes (2551 MB)
    JVM Flags: 3 total; -Xbootclasspath/a:/System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Resources/LauncherSupport.jar -Xms1024M -Xmx2560M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.42 FML v5.0.25.589 Minecraft Forge 7.7.0.589 19 mods loaded, 19 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
    mod_TooManyItems [mod_TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized
    HarkenScythe_Core [HarkenScythe](1.5HarkenScythe_v2.0.1Forgenew.zip) Unloaded->Constructed->Pre-initialized
    BattleTowers [Battle Towers](BattleTowers_1.5.zip) Unloaded->Constructed->Pre-initialized
    eplus [Enchanting Plus](EnchantingPlus-1.13.2.jar) Unloaded->Constructed->Pre-initialized
    Ideas [Ideas](Metallurgy.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Core [Metallurgy 3 Core](Metallurgy.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Base [Metallurgy 3 Base](Metallurgy.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Machines [Metallurgy 3 Machines](Metallurgy.jar) Unloaded->Constructed->Errored
    Metallurgy3Vanilla [Metallurgy 3 Vanilla](Metallurgy.jar) Unloaded->Constructed->Pre-initialized
    teeluk_SpecialArmor [SpecialArmor](SpecialArmor_1.5anew.zip) Unloaded->Constructed->Pre-initialized
    AS_UpdateCheck [AtomicStryker Update Check Mod](UpdateCheckerMod_1.5.zip) Unloaded->Constructed->Pre-initialized
    UpgradePlus [Upgrade Plus](UpgradePlus-15.zip) Unloaded->Constructed->Pre-initialized
    mod_ZanMinimap [mod_ZanMinimap](ZansMinimap1.5.zip) Unloaded->Constructed->Pre-initialized
    Backpack [Backpack](backpack-1.7.8-1.5.zip) Unloaded->Constructed->Pre-initialized
    diamondbuckets [Diamond Buckets 0.96](diamondbuckets_v096.zip) Unloaded->Constructed->Pre-initialized
    IronChest [Iron Chest](ironchest-universal-1.5-5.2.1.288.zip) Unloaded->Constructed->Pre-initialized
    LWJGL: 2.4.2
    OpenGL: ATI Radeon HD 4670 OpenGL Engine GL version 2.1 ATI-1.6.36, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'forge,fml'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by ghost** [comment]
I can explain more detailed, for sure. This problem is not happening in any windows machine, since their file system hierarchy works with backslashes ( C:\Users\User\Downloads\etc ), but it does happen on Linux and Mac (thanks for confirming it for Mac) which use slashes ( / ) in their file system hierarchy instead of the backslashes. 

The problem begins when the program looks for a mod called "Metallurgy.jar" located in .minecraft\mods\Metallurgy.jar This directory hierarchy will never exist neither in Linux nor in Mac, as directories are separated by slashes ( / ). The directory we both have is .minecraft/mods/Metallurgy.jar , so it cannot find the jarfile.

What I've done here for it to work is, first of all, renamed the jarfile to "Metallurgy.jar" (with no " ") and then, copied Metallurgy.jar into the directory which contains .minecraft folder, and called it ".minecraft\mods\Metallurgy.jar" (with no " "). This is the name I gave to the whole file, it is not a location.

For the moment, this is the only way for making it work, so it has to be fixed in advance. I don't know java programming, but I guess this can't be difficult to fix, it's just adding a few lines which tell the program to look for .minecraft\mods\Metallurgy.jar or .minecraft/mods/Metallurgy.jar .

I hope this was helpful.

**Comment by SleepingDragon969** [comment]
Im trying to do what you say but it says I cannot name a file with starting with a dot, it says it is used for the system and will not let me do it.

**Comment by ghost** [comment]
Try calling it whatever and then renaming it in a terminal:
mv "whatever_you_have_called_the_file" .minecraft\mods\Metallurgy.jar . I don't how special characters work on Mac, but in Linux the \ is a special character, so as you name the file, you might have to disable that special meaning that \ might have for you r operating system. In Linux this is done with a \ too, so I had to type: 
cp .minecraft/mods/Metallurgy.jar .minecraft\mods\Metallurgy.jar .
Anyway, you won't probably need anything of this I have said, you just have to find a way to create that file.

**Comment by SleepingDragon969** [comment]
I have my terminal up but have no idea how to rename the file from it. Maybe I should just wait for rebel to fix it as I dont want to fill up this forum with how to fix this little oversight. Hopefully it will be soon.
